/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AEstrella;

//import javax.swing.SwingConstants;
import java.awt.Color;
import javax.swing.*;
/**
 *
 * @author Usuario
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaPI = new java.awt.Label();
        etiquetaPM = new java.awt.Label();
        puzzleInicial = new javax.swing.JPanel();
        ini00 = new javax.swing.JTextField();
        ini12 = new javax.swing.JTextField();
        ini01 = new javax.swing.JTextField();
        ini22 = new javax.swing.JTextField();
        ini11 = new javax.swing.JTextField();
        ini02 = new javax.swing.JTextField();
        ini10 = new javax.swing.JTextField();
        ini21 = new javax.swing.JTextField();
        ini20 = new javax.swing.JTextField();
        puzzleMeta = new javax.swing.JPanel();
        fin01 = new javax.swing.JTextField();
        fin00 = new javax.swing.JTextField();
        fin02 = new javax.swing.JTextField();
        fin10 = new javax.swing.JTextField();
        fin11 = new javax.swing.JTextField();
        fin12 = new javax.swing.JTextField();
        fin20 = new javax.swing.JTextField();
        fin21 = new javax.swing.JTextField();
        fin22 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Método de busqueda A*");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        etiquetaPI.setText("Puzzle Inicial");

        etiquetaPM.setText("Puzzle Meta");

        ini00.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini00.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ini12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ini01.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ini22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ini11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ini02.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ini10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ini21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ini20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ini20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ini20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout puzzleInicialLayout = new javax.swing.GroupLayout(puzzleInicial);
        puzzleInicial.setLayout(puzzleInicialLayout);
        puzzleInicialLayout.setHorizontalGroup(
            puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puzzleInicialLayout.createSequentialGroup()
                .addComponent(ini00, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ini01, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ini02, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(puzzleInicialLayout.createSequentialGroup()
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(puzzleInicialLayout.createSequentialGroup()
                        .addComponent(ini10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ini11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(puzzleInicialLayout.createSequentialGroup()
                        .addComponent(ini20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ini21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ini22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        puzzleInicialLayout.setVerticalGroup(
            puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puzzleInicialLayout.createSequentialGroup()
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ini00, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini01, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini02, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ini11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ini22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ini20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        fin01.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fin00.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin00.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fin02.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fin10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fin11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fin12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fin20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fin21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fin22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fin22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fin22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout puzzleMetaLayout = new javax.swing.GroupLayout(puzzleMeta);
        puzzleMeta.setLayout(puzzleMetaLayout);
        puzzleMetaLayout.setHorizontalGroup(
            puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puzzleMetaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fin00, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(fin10)
                    .addComponent(fin20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fin11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(fin01, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fin21, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fin02, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(fin12)
                    .addComponent(fin22))
                .addGap(4, 4, 4))
        );
        puzzleMetaLayout.setVerticalGroup(
            puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puzzleMetaLayout.createSequentialGroup()
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fin01, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin00, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin02, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fin10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(puzzleMetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fin20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fin22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Abiertos", "Cerrados"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
        }

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setEditable(false);
        jScrollPane1.setViewportView(textArea);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Downloads\\search.png")); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(puzzleInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puzzleMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(puzzleInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(puzzleMeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label etiquetaPI;
    private java.awt.Label etiquetaPM;
    private javax.swing.JTextField fin00;
    private javax.swing.JTextField fin01;
    private javax.swing.JTextField fin02;
    private javax.swing.JTextField fin10;
    private javax.swing.JTextField fin11;
    private javax.swing.JTextField fin12;
    private javax.swing.JTextField fin20;
    private javax.swing.JTextField fin21;
    private javax.swing.JTextField fin22;
    private javax.swing.JTextField ini00;
    private javax.swing.JTextField ini01;
    private javax.swing.JTextField ini02;
    private javax.swing.JTextField ini10;
    private javax.swing.JTextField ini11;
    private javax.swing.JTextField ini12;
    private javax.swing.JTextField ini20;
    private javax.swing.JTextField ini21;
    private javax.swing.JTextField ini22;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel puzzleInicial;
    private javax.swing.JPanel puzzleMeta;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
